name: Deploy
on:
  push:
    branches:
      - prod
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        working-directory: backend/ResQueue
        run: dotnet publish --os linux --arch amd64 /t:PublishContainer -p:ContainerRepository=filipbekic01/resqueue -p:ContainerRegistry=ghcr.io
