name: Deploy
on:
  push:
    branches:
      - prod
jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      NuGetApiKey: ${{ secrets.NUGET_API_KEY }}
      IsCI: "true"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Node dependencies
        working-directory: frontend
        run: npm ci

      - name: Build Vue frontend
        working-directory: frontend
        run: npm run build:prod

      - name: Copy Vue dist to wwwroot
        run: |
          rm -rf backend/ResQueue/ResQueue/wwwroot
          cp -R frontend/dist backend/ResQueue/ResQueue/wwwroot

      - name: Build the project
        working-directory: backend/ResQueue/ResQueue
        run: dotnet build --configuration Release

      - name: Pack the NuGet package
        working-directory: backend/ResQueue/ResQueue
        run: dotnet pack --configuration Release

      - name: Push the NuGet package
        working-directory: backend/ResQueue/ResQueue
        run: dotnet nuget push bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://nuget.org
